# Site settings
title: Ziven's blog
description: A blog about Ziven
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ziven
user_description: Hi :)
user_title: Computer Vision
email: yangziwen1994@gmail.com
twitter_username: 
github_username:  zivenyang
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
